#include "scmhob.h"


SCM call_with_optional_args();
SCM call_with_optional_args_fn2();
SCM assoc_set_excl_();
SCM assoc_get();
SCM make_config();
SCM make_schema();
SCM schema_pred_();
SCM make_setting();
SCM config_set_excl_();
SCM config_get();
SCM config_get_cl2();
SCM config_get_cl1();
SCM config_get_cl1_cl3();
SCM print_config();
SCM print_config_fn4();
SCM cfg_colon_validate();
SCM register_config();
SCM find_config();
SCM cfg_colon_save();
SCM cfg_colon_load();
SCM hello_world();
SCM top_actions_1_cfg();
SCM top_actions_cfg();
SCM map1();
SCM map1_inst1();
SCM for_each1();
SCM make_setting_wrapper();
SCM assoc_get_wrapper();
SCM init_1_cfg();
SCM init_cfg();
SCM *define_record_type;
SCM *options;
SCM *config_options;
SCM *parent;
SCM *config_parent;
SCM *schema;
SCM *doc;
SCM *config_doc;
SCM *set_config_name_excl_;
SCM *config_pred_;
SCM *name;
SCM *_less_config_grtr_;
SCM *config_schema;
SCM *config_name;
SCM *call_with_values;
SCM *settings;
SCM *set_config_options_excl_;
SCM *set_config_parent_excl_;
SCM *set_config_settings_excl_;
SCM *set_config_schema_excl_;
SCM *set_config_doc_excl_;
SCM *_percent_make_config;
SCM *values;
SCM *nonum_prefix_1_plus_;
SCM *apply_nonkeyword;
SCM *error;
SCM *configs_global;
SCM *schemas_global;
static SCM config_get_cl1_cl3_clproc0;
static SCM config_get_cl2_clproc0;
static SCM config_get_cl1_clproc0;
static SCM type_symb;
static SCM cfg_colon_schema_symb;
static SCM name_symb;
static SCM settings_symb;
static SCM const_1;
static SCM const_2;
static SCM const_3;
static SCM const_4;
static SCM const_5;
static SCM const_6;
static SCM const_7;
static SCM const_8;

